name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run linting
      run: swiftlint --strict
    - name: Run tests
      run: swift test --enable-code-coverage
    - name: Run coverage
      run: ./cov.sh
